# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zqQr_L8bHRfOashfy9GnOhqbBtBmrMfm
"""

import pandas as pd

df=pd.read_csv("/content/delivery_delay - delivery_delay (1).csv")

df

X=df.drop("Delivery_Delay",axis=1)
y=df['Delivery_Delay']

from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

from sklearn.linear_model import LogisticRegression
model=LogisticRegression(max_iter=1000)
model.fit(X_train,y_train)

X.columns

model.predict([[20,3,1,2,5,2,3,3,120,12,100]])

model.predict_proba([[20,3,1,2,5,2,3,3,120,12,100]])

model.score(X_test,y_test)

from sklearn.metrics import confusion_matrix
y_pred=model.predict(X_test)
cm=confusion_matrix(y_test,y_pred)
cm

from sklearn.metrics import recall_score

recall = recall_score(y_test, y_pred)
print(f"Recall on test data: {recall:.4f}")

from sklearn.model_selection import cross_val_score, StratifiedKFold

# Define the cross-validation strategy
kf = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)

# Perform cross-validation with 'recall' as the scoring metric
cv_recall_scores = cross_val_score(model, X, y, cv=kf, scoring='recall')

print(f"Cross-validation Recall Scores: {cv_recall_scores}")
print(f"Mean Cross-validation Recall: {cv_recall_scores.mean():.4f}")
print(f"Standard Deviation of Cross-validation Recall: {cv_recall_scores.std():.4f}")

from sklearn.metrics import roc_curve, auc
import matplotlib.pyplot as plt

# Get predicted probabilities for the positive class
y_pred_proba = model.predict_proba(X_test)[:, 1]

# Calculate ROC curve values
fpr, tpr, thresholds = roc_curve(y_test, y_pred_proba)

# Calculate AUC
roc_auc = auc(fpr, tpr)

print(f"AUC on test data: {roc_auc:.4f}")

# Plot the ROC curve
plt.figure(figsize=(8, 6))
plt.plot(fpr, tpr, color='darkorange', lw=2, label=f'ROC curve (area = {roc_auc:.2f})')
plt.plot([0, 1], [0, 1], color='navy', lw=2, linestyle='--')
plt.xlim([0.0, 1.0])
plt.ylim([0.0, 1.05])
plt.xlabel('False Positive Rate')
plt.ylabel('True Positive Rate')
plt.title('Receiver Operating Characteristic (ROC) Curve')
plt.legend(loc='lower right')
plt.grid(True)
plt.show()

"""### Interpretation of Cross-validation Recall:

*   The `Cross-validation Recall Scores` show the recall value for each fold.
*   The `Mean Cross-validation Recall` gives you an average estimate of the model's recall across different data splits, which is a more reliable indicator than a single train-test split.
*   The `Standard Deviation` indicates how much the recall scores vary across the folds. A low standard deviation suggests consistency in performance.
"""

from sklearn.tree import DecisionTreeClassifier

# Initialize the Decision Tree Classifier with a max_depth of 2
decision_tree_model = DecisionTreeClassifier(max_depth=2, random_state=42)

# Train the model
decision_tree_model.fit(X_train, y_train)

print("Decision Tree Model (max_depth=2) trained successfully:")
print(decision_tree_model)

from sklearn.tree import plot_tree
import matplotlib.pyplot as plt

plt.figure(figsize=(20, 10))
plot_tree(decision_tree_model,
          feature_names=X.columns.tolist(),
          class_names=['No Delay', 'Delay'],
          filled=True,
          rounded=True,
          fontsize=10)
plt.title('Decision Tree Classifier (Max Depth = 2)', fontsize=15)
plt.show()

"""The plot above visualizes the Decision Tree with a maximum depth of 2. Each node represents a decision rule based on a feature, leading to a classification (No Delay or Delay) at the leaf nodes. The `value` array in each node shows the count of samples belonging to each class in that node (e.g., `[no_delay_samples, delay_samples]`). The `gini` value indicates the impurity of the node."""

import joblib

joblib.dump(model, 'model.sav')